#ifndef INPUT_H
#define INPUT_H

#include <string>

#define NUM_KEYS GLFW_KEY_LAST + 1

//Defining these to allow for an eaiser swith between input libraries

#define KEY_SPACE GLFW_KEY_SPACE
#define KEY_ESC GLFW_KEY_ESC
#define KEY_F1 GLFW_KEY_F1
//TODO: Finish defining special keys
/*GLFW_KEY_UP
GLFW_KEY_DOWN
GLFW_KEY_LEFT
GLFW_KEY_RIGHT
GLFW_KEY_LSHIFT
GLFW_KEY_RSHIFT
GLFW_KEY_LCTRL
GLFW_KEY_RCTRL
GLFW_KEY_LALT
GLFW_KEY_RALT
GLFW_KEY_LSUPER
GLFW_KEY_RSUPER
GLFW_KEY_TAB
GLFW_KEY_ENTER
GLFW_KEY_BACKSPACE
GLFW_KEY_INSERT
GLFW_KEY_DEL
GLFW_KEY_PAGEUP
GLFW_KEY_PAGEDOWN
GLFW_KEY_HOME
GLFW_KEY_END
GLFW_KEY_KP_n
GLFW_KEY_KP_DIVIDE
GLFW_KEY_KP_MULTIPLY
GLFW_KEY_KP_SUBTRACT
GLFW_KEY_KP_ADD
GLFW_KEY_KP_DECIMAL
GLFW_KEY_KP_EQUAL
GLFW_KEY_KP_ENTER
GLFW_KEY_KP_NUM_LOCK
GLFW_KEY_CAPS_LOCK
GLFW_KEY_SCROLL_LOCK
GLFW_KEY_PAUSE
GLFW_KEY_MENU*/

namespace Input
{
  void initInput();
  bool getKeyState(std::string key);
  void addMapping(std::string name, int key);
}

#endif
